name: DDK Build Kernel Module

on:
  workflow_call:
    inputs:
      kmi:
        required: true
        type: string
      ddk_release:
        required: false
        default: '20251016'
        type: string
      module_name:
        required: false
        default: 'android-wuwa'
        type: string

jobs:
  build-module:
    name: Build for ${{ inputs.kmi }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ylarod/ddk:${{ inputs.kmi }}-${{ inputs.ddk_release }}
      options: --privileged

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build module
        run: |
          make KDIR=$KERNEL_SRC

          mkdir -p /github/workspace/out

          KVER=$(echo "${{ inputs.kmi }}" | awk -F'-' '{print $2}')
          OUTPUT_NAME="${KVER}.ko"

          cp "${{ inputs.module_name }}.ko" "/github/workspace/out/$OUTPUT_NAME"

          llvm-strip -d "/github/workspace/out/$OUTPUT_NAME"

          ls -lh "/github/workspace/out/$OUTPUT_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.kmi }}
          path: /github/workspace/out/*.ko
